name: Android Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: |
        export GRADLE_OPTS="-Xmx4g -Xms1g"
        ./gradlew clean --no-daemon
        ./gradlew build --no-daemon --max-workers=2 --no-build-cache

    - name: Upload build artifacts
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: android-build-output
        path: |
          app/build/outputs/
          build/reports/
