name: Android Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: |
        export GRADLE_OPTS="-Xmx6g -Xms2g -Dorg.gradle.daemon=false -Dorg.gradle.parallel=false"
        ./gradlew clean --no-daemon --no-build-cache
        ./gradlew assembleDebug --no-daemon --no-build-cache --max-workers=1

    - name: Upload build artifacts
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: android-build-output
        path: |
          app/build/outputs/
          build/reports/
